version: '4'

services:
  albumserver:
    container_name: albumserver
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  albumfrontend:
    container_name: albumfrontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ./frontend/.env


  albumclient:
    container_name: albumclient
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: ./client/src
          ignore: 
            - node_modules
        - action: rebuild
          path: ./client/package.json




volumes:
  album_build:
