[[services]]
  internal_port = 3306
  protocol = "tcp"
  envfile = ".env"

# M채채ritet채채n build- ja run-komennot
[build]
  command = "python manage.py migrate"

[run]
  command = "python manage.py runserver 0.0.0.0:$PORT"