# Generated by Django 4.2.4 on 2023-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='description',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
